M48
; DRILL file KiCad 10.0.4 date 2026-08-16T19:36:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-16T19:36:20+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X175.01Y-78.04
X180.79Y-78.04
T2
X136.0Y-77.0
X136.0Y-124.0
X224.0Y-77.0
X224.0Y-124.0
M30
