M48
; DRILL file KiCad 10.0.4 date 2026-07-21T17:00:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-21T17:00:12+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X103.25Y-52.318
T2
X85.0Y-47.5
X85.0Y-102.5
X155.0Y-47.5
X155.0Y-102.5
M30
